name: deploy-staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # SSH into server and run deploy script
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      # SSH into server and run deploy script
      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST  }} './run-tests.sh' 